REVERT ME, test quickly how it looks

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -6,6 +6,11 @@ on:
       - r[0-9]+ # Trigger builds after a push to weekly branches
   pull_request:
 
+permissions:
+  contents: read
+  actions: read
+  checks: write
+
 concurrency:
   # Cancel any running workflow for the same branch when new commits are pushed.
   # We group both by ref_name (available when CI is triggered by a push to a branch/tag)
@@ -38,6 +43,13 @@ jobs:
         run: make check/go/mod
       - name: Test
         run: make go/test
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Go Tests            # Name of the check run which will be created
+          path: .go-test.junit.xml
+          reporter: java-junit              # Format of test results
       - uses: actions/upload-artifact@v3  # upload test results
         if: success() || failure()        # run this step even if previous step failed
         with:
